; PlatformIO Project Configuration File
; Target: Arduino Uno
; Project: Multi-function Clock / Alarm / Countdown / Stopwatch
;          with IR remote control, DS1302 RTC, DHT11, 16x2 I2C LCD.

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

lib_deps =
    z3t0/IRremote @ ^4.4.0
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    makuna/RTC @ ^2.5.0
